"""Generate the firmware headers: model byte arrays, normalisation constants and
an on-device self test built from held-out test windows.

Why the self test stores raw sensor counts
------------------------------------------
The windows are converted back into the 16-bit two's complement values that the
MPU6050 would return from registers 0x3B..0x48 at +-16 g / +-2000 deg/s. The
firmware therefore runs them through exactly the same path as live I2C data:
counts -> g / deg/s -> standardisation -> int8 quantisation -> interpreter.
That makes the self test evidence that the deployed pipeline is correct, not
just that the interpreter runs.

Run:  python -m training.export_firmware [variant]
"""

from __future__ import annotations

import sys
import textwrap
from pathlib import Path

import numpy as np

from training import config as C
from training.data import Dataset

# MPU6050 sensitivities for the ranges the firmware configures.
ACCEL_LSB_PER_G = 32768.0 / C.MPU6050_ACCEL_RANGE_G        # 2048 LSB/g  @ +-16 g
GYRO_LSB_PER_DPS = 32768.0 / C.MPU6050_GYRO_RANGE_DPS      # 16.384 LSB/(deg/s) @ +-2000 dps


def to_raw_counts(window: np.ndarray) -> np.ndarray:
    """(128, 6) in g / deg/s -> int16 register values."""
    counts = np.empty_like(window, dtype=np.int32)
    counts[:, :3] = np.rint(window[:, :3] * ACCEL_LSB_PER_G)
    counts[:, 3:] = np.rint(window[:, 3:] * GYRO_LSB_PER_DPS)
    return np.clip(counts, -32768, 32767).astype(np.int16)


def c_byte_array(name: str, blob: bytes, width: int = 12) -> str:
    body = ",".join(f"0x{b:02x}" for b in blob)
    wrapped = textwrap.fill(body, width=width * 6, break_long_words=False)
    wrapped = textwrap.indent(wrapped, "    ")
    return (
        f"const unsigned int {name}_len = {len(blob)};\n"
        f"alignas(16) const unsigned char {name}[] = {{\n{wrapped}\n}};\n"
    )


def c_int16_array(name: str, arr: np.ndarray) -> str:
    body = ",".join(str(int(v)) for v in arr.ravel())
    wrapped = textwrap.indent(textwrap.fill(body, width=96, break_long_words=False), "    ")
    return f"const int16_t {name}[] = {{\n{wrapped}\n}};\n"


def cfloat(value: float) -> str:
    """C float literal that always carries a decimal point (`2048f` is invalid C++)."""
    text = f"{float(value):.8g}"
    if "." not in text and "e" not in text and "E" not in text:
        text += ".0"
    return text + "f"


def c_float_array(name: str, arr: np.ndarray) -> str:
    body = ", ".join(cfloat(v) for v in np.asarray(arr).ravel())
    return f"const float {name}[] = {{ {body} }};\n"


def pick_selftest(ds: Dataset) -> tuple[np.ndarray, np.ndarray, list[str]]:
    """Class-stratified, deterministic pick of held-out TEST windows."""
    X, y = ds.split("test", normalized=False, model_layout=False)
    trials = ds.trials("test")
    subjects = ds.subjects("test")
    rng = np.random.default_rng(C.SEED)

    windows, labels, tags = [], [], []
    for k in range(C.N_CLASSES):
        idx = np.flatnonzero(y == k)
        take = rng.choice(idx, size=min(C.SELFTEST_WINDOWS_PER_CLASS, idx.size), replace=False)
        for i in sorted(take):
            windows.append(X[i])
            labels.append(k)
            tags.append(f"{subjects[i]}/{trials[i]}")
    return np.stack(windows), np.asarray(labels, dtype=np.int8), tags


def main(argv: list[str]) -> None:
    variant = argv[0] if argv else "small"
    ds = Dataset()

    int8_path = C.MODELS_DIR / f"har_{variant}_int8.tflite"
    f32_path = C.MODELS_DIR / f"har_{variant}_float32.tflite"
    for p in (int8_path, f32_path):
        if not p.exists():
            sys.exit(f"{p} missing - run `python -m training.quantize` first")
    int8_blob = int8_path.read_bytes()
    f32_blob = f32_path.read_bytes()

    windows, labels, tags = pick_selftest(ds)
    counts = np.stack([to_raw_counts(w) for w in windows])

    C.FIRMWARE_DIR.mkdir(parents=True, exist_ok=True)
    out = C.FIRMWARE_DIR / "model_data.h"

    header = f"""\
// Generated by training/export_firmware.py - do not edit by hand.
//
// deployed variant : {variant}
// int8 model       : {int8_path.name} ({len(int8_blob)} bytes)
// float32 model    : {f32_path.name} ({len(f32_blob)} bytes)
//
// The float32 model is embedded only so that the firmware can benchmark
// float32 against int8 on the device itself (latency and arena usage).

#pragma once
#include <stdint.h>

#define HAR_WINDOW        {C.WINDOW}
#define HAR_CHANNELS      {C.N_CHANNELS}
#define HAR_NUM_CLASSES   {C.N_CLASSES}
#define HAR_SAMPLE_RATE_HZ {C.FS_HZ}
#define HAR_STRIDE        {C.STRIDE}
#define HAR_MODEL_VARIANT "{variant}"

// MPU6050 configuration assumed by the exported constants.
#define HAR_ACCEL_RANGE_G     {C.MPU6050_ACCEL_RANGE_G}
#define HAR_GYRO_RANGE_DPS    {C.MPU6050_GYRO_RANGE_DPS}
#define HAR_ACCEL_LSB_PER_G   {cfloat(ACCEL_LSB_PER_G)}
#define HAR_GYRO_LSB_PER_DPS  {cfloat(GYRO_LSB_PER_DPS)}

static const char* const kHarClassNames[HAR_NUM_CLASSES] = {{ {
        ", ".join(f'"{n}"' for n in C.CLASS_NAMES)} }};

// Per-channel standardisation, computed on the TRAIN split only.
// order: ax, ay, az [g], gx, gy, gz [deg/s]
{c_float_array("kHarNormMean", ds.mean)}{c_float_array("kHarNormStd", ds.std)}

// ---------------------------------------------------------------- self test --
// {len(windows)} held-out windows from the subject-wise TEST split, stored as raw
// int16 MPU6050 register values. Source trials:
{chr(10).join(f"//   [{i}] {tags[i]:>22s} -> {C.CLASS_NAMES[labels[i]]}" for i in range(len(tags)))}
#define HAR_SELFTEST_COUNT {len(windows)}
{c_int16_array("kHarSelfTestRaw", counts)}
const int8_t kHarSelfTestLabels[HAR_SELFTEST_COUNT] = {{ {
        ", ".join(str(int(v)) for v in labels)} }};

// ------------------------------------------------------------------- models --
{c_byte_array("kHarModelInt8", int8_blob)}
{c_byte_array("kHarModelFloat32", f32_blob)}
"""
    out.write_text(header)
    print(f"wrote {out} ({out.stat().st_size} bytes)")
    print(f"  int8 model     {len(int8_blob):6d} B")
    print(f"  float32 model  {len(f32_blob):6d} B")
    print(f"  self test      {len(windows)} windows, "
          f"{counts.nbytes} B of int16 sensor counts")


if __name__ == "__main__":
    main(sys.argv[1:])
