"""Emit firmware/har_esp32/model_zoo.h: every (variant, precision) model in one
header so the ESP32 can benchmark all of them in a single simulation run.

This is what turns the Pareto frontier from a host-side proxy into device
measurements: latency and tensor-arena usage for all six candidates are measured
on the ESP32 itself, not estimated from the desktop interpreter.

Run:  python -m training.export_model_zoo
"""

from __future__ import annotations

import numpy as np

from training import config as C
from training.export_firmware import c_byte_array

PRECISIONS = ("float32", "int8")


def main() -> None:
    entries = []
    for variant in C.MODEL_VARIANTS:
        for precision in PRECISIONS:
            path = C.MODELS_DIR / f"har_{variant}_{precision}.tflite"
            if not path.exists():
                print(f"skip {path.name} (missing)")
                continue
            entries.append((variant, precision, path.read_bytes()))

    if not entries:
        raise SystemExit("no .tflite models found - run `python -m training.quantize`")

    parts = [
        "// Generated by training/export_model_zoo.py - do not edit by hand.",
        "//",
        "// All candidate models, used only by the RUN_MODEL_ZOO build to measure",
        "// latency and arena usage of every point on the Pareto frontier on device.",
        "",
        "#pragma once",
        "#include <stdint.h>",
        "",
    ]
    for variant, precision, blob in entries:
        parts.append(c_byte_array(f"kZoo_{variant}_{precision}", blob))
        parts.append("")

    parts.append("struct HarZooEntry {")
    parts.append("  const char* variant;")
    parts.append("  const char* precision;")
    parts.append("  const unsigned char* data;")
    parts.append("  unsigned int length;")
    parts.append("};")
    parts.append("")
    parts.append(f"#define HAR_ZOO_COUNT {len(entries)}")
    parts.append("static const HarZooEntry kHarZoo[HAR_ZOO_COUNT] = {")
    for variant, precision, _ in entries:
        name = f"kZoo_{variant}_{precision}"
        parts.append(f'  {{ "{variant}", "{precision}", {name}, {name}_len }},')
    parts.append("};")
    parts.append("")

    out = C.FIRMWARE_DIR / "model_zoo.h"
    out.write_text("\n".join(parts))
    total = sum(len(b) for _, _, b in entries)
    print(f"wrote {out} ({out.stat().st_size} bytes)")
    for variant, precision, blob in entries:
        print(f"  {variant:6s} {precision:8s} {len(blob):6d} B")
    print(f"  total model bytes embedded: {total}")


if __name__ == "__main__":
    main()
