"""Turn held-out test windows into Wokwi automation scenarios.

Each scenario replays one real 2.56 s window through the *simulated MPU6050*,
one sample every 20 ms, by driving the part's automation controls. The firmware
therefore reads the data over I2C exactly as it would read a physical sensor -
nothing about the classification is hard coded in the firmware.

Because the scenario and the firmware clock are independent, the window is
played twice (plus a lead-in) so that at least one complete 128-sample window is
captured regardless of phase.

Run:  python -m training.export_wokwi
"""

from __future__ import annotations

import numpy as np

from training import config as C
from training.data import Dataset

CONTROLS = ("accelX", "accelY", "accelZ", "rotationX", "rotationY", "rotationZ")
PART_ID = "imu1"
SAMPLE_MS = int(1000 / C.FS_HZ)
REPEATS = 4                   # 4 x 2.56 s -> several overlapping windows
LEAD_IN_SAMPLES = 40          # 0.8 s of the first sample, lets the ring fill


def pick_window(ds: Dataset, label: int) -> tuple[np.ndarray, str]:
    """Pick a *representative* window of a class.

    Selection rule: describe every window of the class by the per-channel mean
    and standard deviation over time (12 numbers), robust-scale those features
    across the class, and take the window closest to the class median.

    Averaging raw samples would not work here: the time-average of many walking
    windows cancels the oscillation, so "closest to the mean waveform" returns
    the least dynamic window of the class. Matching the median of the summary
    statistics instead returns a window with typical energy, and the choice is
    made without ever looking at the model's prediction.
    """
    X, y = ds.split("test", normalized=False, model_layout=False)
    subj = ds.subjects("test")
    trials = ds.trials("test")
    idx = np.flatnonzero(y == label)

    Z = ds.normalize(X[idx])
    feats = np.concatenate([Z.mean(axis=1), Z.std(axis=1)], axis=1)
    median = np.median(feats, axis=0)
    scale = np.median(np.abs(feats - median), axis=0)
    scale = np.where(scale < 1e-6, 1.0, scale)
    best = idx[int(np.argmin(np.abs((feats - median) / scale).sum(axis=1)))]
    return X[best], f"{subj[best]}/{trials[best]}"


def scenario_yaml(name: str, source: str, window: np.ndarray, expect: str) -> str:
    lines = [
        f"# Generated by training/export_wokwi.py - do not edit by hand.",
        f"# Source: held-out SisFall test window {source} (class {expect})",
        f"# {C.WINDOW} samples @ {C.FS_HZ} Hz replayed {REPEATS}x through the simulated MPU6050.",
        f"name: '{name}'",
        "version: 1",
        "author: 'AIoT course project'",
        "",
        "steps:",
        "  - wait-serial: 'READY'",
    ]

    def emit_sample(sample: np.ndarray, delay_ms: int) -> None:
        for control, value in zip(CONTROLS, sample):
            lines.append("  - set-control:")
            lines.append(f"      part-id: {PART_ID}")
            lines.append(f"      control: {control}")
            lines.append(f"      value: {value:.4f}")
        lines.append(f"  - delay: {delay_ms}ms")

    # hold the first sample so the 128-sample ring buffer is primed
    emit_sample(window[0], LEAD_IN_SAMPLES * SAMPLE_MS)
    for _ in range(REPEATS):
        for sample in window:
            emit_sample(sample, SAMPLE_MS)

    # The scenario passes only if the firmware actually reports the class of the
    # replayed window. Asserted on the raw per-window prediction; the smoothed
    # value needs a majority of three windows and is reported separately.
    lines.append(f"  - wait-serial: 'PRED {expect}'")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    C.WOKWI_SCENARIO_DIR.mkdir(parents=True, exist_ok=True)
    ds = Dataset()
    for label, cls in enumerate(C.CLASS_NAMES):
        window, source = pick_window(ds, label)
        text = scenario_yaml(f"{cls.lower()} window replay", source, window, cls)
        path = C.WOKWI_SCENARIO_DIR / f"{cls.lower()}.yaml"
        path.write_text(text)
        print(f"wrote {path}  ({len(text.splitlines())} lines, source {source})")

        peak = float(np.linalg.norm(window[:, :3], axis=1).max())
        print(f"    peak |a| = {peak:.2f} g   "
              f"gyro max = {np.abs(window[:, 3:]).max():.0f} deg/s")


if __name__ == "__main__":
    main()
